version: '3.5'
services:
  typoteka.uploader.mongo:
    image: mongo
    restart: always
    container_name: typoteka.uploader.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: typoteka-uploader

    ports:
      - 27018:27017

    volumes:
      - typoteka.mongo.uploader:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-uploader --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  typeoteka.uploader.mongo.ui:
    image: mongo-express
    restart: always
    container_name: typeoteka.uploader.mongo.ui
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@typoteka.uploader.mongo:27017/

volumes:
  typoteka.mongo.uploader:
